---
title: "Wrestling with Faith"
author: "Andew Holz"
---

Wrestling with Faith Public ContentAnyone can view this post Posted by Andrew Holz on 06/07/2023 - 4:48pm

People are thinking deeply about what they believe and still have questions. Some people claim they are spiritual but not religious. Podcasts are built around the idea of deconstructing faith. Unfortunately, it’s a lonely path. Support is hard to find for those who are questioning what they have been taught. Online communities provide some support but not in person spiritual community.

This forum will provide an opportunity to consider and discuss your faith (if you want, no pressure) with other people on a similar spiritual journey. The first session will focus on the process of rethinking your beliefs. After that, each week will focus on one topic, including the big questions of life such as the problem of evil and whether God exists. Each session will consist of reviewing early beliefs, the questions that have arisen, and what your current beliefs are. Lastly, the Quaker hosts will address what early Quakerism has to say about that topic, so you can consider how that meshes (or doesn’t) with your own beliefs.

Quakerism was formed in 1650s in England by spiritual seekers, people who were wrestling their own faith. Some of their answers may still be relevant, and some may not. Today’s Quakers don’t always agree and still wrestle with many of these issues.

The forum will be hosted by Plainfield Quakers. You are welcome to attend silent worship with the Quakers at 10.30 am in the historic meetinghouse and stay for the Forum. Or you can just attend the Forum, which starts at 12 noon with a light lunch.

Please register for the free forum by clicking on this Eventbrite link or by emailing clerk\@plainfieldquakers.org so that the hosts can plan for the lunch. There is no cost to attend, but donations are accepted.

Tentative schedule (Second and Fourth Sundays of the month, skipping Easter)

```         
June 11:-- 
Is the Bible inerrant?  How do we use the Bible in our faith journey? What did early Quakers believe about the Bible?

-- Please Signup
```
