---
title: "Quaker Testimonies"
author: "Andrew Holz"
---

In the Religious Society of Friends, our faith is expressed through our testimonies. These are not just statements of belief but are reflections of the divine within us that guide our daily actions and decisions. As Friends, we strive to live by these principles, which we believe are universal truths illuminated by the Light within each of us.

**Simplicity**: We seek a simple life, focused on what is truly important and letting go of what distracts us from our spiritual goals. This means prioritizing our inner spiritual experience over material wealth and outward appearances.

**Peace**: We are dedicated to living in a manner that reflects our deep commitment to peace. We believe in resolving conflicts through understanding and respect, and we oppose all forms of violence. Our peace testimony leads us to advocate for peaceful solutions globally and in our communities.

**Integrity**: We strive to live lives of authenticity and truthfulness, ensuring that our actions reflect our deepest beliefs. Our commitment to integrity means we speak our truth, with the weight of our words matching the depth of our hearts.

**Community**: Our sense of community is foundational. We support one another in our spiritual journeys and work together to reflect our collective Light. This involves inclusive and supportive fellowship, where each voice is valued.

**Equality**: We hold that there is that of God in everyone, and this belief drives our deep respect for the equality of all persons. We work to remove barriers that prevent people from living as their true selves, promoting equity and justice for every individual.

**Stewardship of the Earth**: Recognizing the Earth as a precious gift, we take action to care for it responsibly. We promote sustainability in our practices and decisions, reflecting our reverence for the natural world.

Through our testimonies, we embody the principles of our faith, aiming to live in a way that brings these values to light in the world. As we gather in silence and speak when moved, we listen deeply to the Spirit and to each other, seeking the ways our lives can speak of the truths we hold dear.